

#' graph.sample
#'
#' Return ggplot graphics to resume the sample.
#'
#' @param x BSS table for one sample
#' @param metadata metadata table generated by "check_metadata"
#' @param bv.type elli, plain or riddled biovolume
#' @param living.only TRUE by default
#' @param taxo taxonomic table generated with "add_trophic" and "add_taxo"
#'
#' @return A set of graphics to resume the sample.
#' @export
#'
#' @examples

graph.sample <- function(x, metadata, taxo, bv.type="elli", living.only=T) {
  # ameioration ==> memes couleurs pour memes taxons
  # ameioration ==> toujours avoir un niveau 6 ou utiliser la table de zoe


  # Select type of biovolume
  x <- filter(x, type==bv.type)

  # Unite taxonomiques
  x <- merge(x, taxo, "object_annotation_hierarchy", all.x=T)

  # Filter living
  if (living.only==T) {
    x <- filter(x, n1=="living")
    taxo <- filter(taxo, n1=="living")
  }

  # Define colors according to common taxonomy vector
  N <- length(unique(taxo$Sub_type))
  myColors <- colorRampPalette(brewer.pal(8, "Set2"))(N)
  names(myColors) <- unique(taxo$Sub_type)

  # ------------------------------------------------------------------------------
  # Resume
  div <- x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()
  text = paste0(
    "\n\nTotal absolute abundance (ind.m-3):\n",
    round(sum(x$AB, na.rm=T),4),
    "\nTotal absolute biovolume (mm3.mm-3):\n",
    round(sum(x$BV, na.rm=T),4),
    "\nShannon Index:\n",
    round(div,4))
  p1 <- ggplot() +
    annotate("text", x = 1, y=10, size=3, label = text) +
    theme_void()

  # Relative abundance
  tot <- sum(sum(x$AB, na.rm=T))

  p2 <- x %>% group_by(Sub_type) %>%
    summarise(per=sum(AB, na.rm=T)/tot*100) %>%
    ggplot(aes(x="", y=per, fill=Sub_type)) +
    geom_bar(stat="identity", width=1, color="white") +
    scale_fill_manual(values = myColors) +
    coord_polar("y", start=0) +
    ggtitle("Relative abundance") +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5))

  # Relative biovolume
  tot <- sum(sum(x$BV, na.rm=T))

  p3 <- x %>% group_by(Sub_type) %>%
    summarise(per=sum(BV, na.rm=T)/tot*100) %>%
    ggplot(aes(x="", y=per, fill=Sub_type)) +
    geom_bar(stat="identity", width=1, color="white") +
    scale_fill_manual(values = myColors) +
    coord_polar("y", start=0) +
    ggtitle("Relative biovolume") +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5))

  # NBSS
  p4 <- x %>%
    ggplot(aes(x=bv_to_esdum(max), y=BV/norm)) +
    stat_summary(fun = sum, na.rm=T, geom="point", size=3) +
    stat_summary(fun = sum, na.rm=T, geom="line", size=1) +
    scale_x_log10("Size (\u00b5m)") +
    scale_y_log10("NBSS (mm\u00b3.mm\u207B\u00b3.m\u207B\u00b3)", labels=trans_format('log10',math_format(10^.x))) +
    theme_minimal() +
    ggtitle("NBSS") +
    theme(plot.title = element_text(hjust = 0.5))

  # BSS
  p5 <- x %>%
    ggplot(aes(x=bv_to_esdum(max), y=BV)) +
    stat_summary(fun = sum, na.rm=T, geom="point", size=3) +
    stat_summary(fun = sum, na.rm=T, geom="line", size=1) +
    scale_x_log10("Size (\u00b5m)") +
    scale_y_log10("BSS (mm\u00b3.m\u207B\u00b3)", labels=trans_format('log10',math_format(10^.x))) +
    theme_minimal() +
    ggtitle("BSS") +
    theme(plot.title = element_text(hjust = 0.5))

  # BV compo/size class
  p6 <- x %>% group_by(Sub_type, max, class) %>%
    group_by(class) %>% mutate(per = BV/sum(BV, na.rm=T)*100) %>%
    group_by(class, max, Sub_type) %>% summarise(per=sum(per, na.rm=T)) %>%
    ggplot(aes(x=bv_to_esdum(max), y=per, fill=Sub_type)) +
    geom_col() +
    scale_fill_manual(values = myColors) +
    ylab("Biovolume (%)") +
    scale_x_log10("Size (\u00b5m)") +
    theme_minimal()

  # Trophic pyramid p7
  x$categorie[x$Value==1] <- "Phototrophs"
  x$categorie[x$Value==1.5] <- "Mixotrophs"
  x$categorie[x$Value==2] <- "Grazers"
  x$categorie[x$Value==2.5] <- "Omnivorous"
  x$categorie[x$Value==3] <- "Predators"
  x$categorie[x$Value==3.5] <- "Unknown"
  x$categorie[x$Value==-1] <- "None"

  p7 <- ggplot(x, aes(x=reorder(categorie,Value), y=BV)) +
    geom_col() +
    scale_fill_brewer(palette="Set2") +
    coord_flip() +
    xlab(NULL) +
    ylab("Biovolume (mm\u00b3.m\u207B\u00b3)") +
    theme_minimal()

  # Map
  meta.x <- filter(metadata, sample_id==unique(x$sample_id))
  # ex = 3
  # latmin <- min(meta.x$object_lat, na.rm=T)-ex
  # lonmin <- min(meta.x$object_lon, na.rm=T)-ex
  # latmax <- max(meta.x$object_lat, na.rm=T)+ex
  # lonmax <- max(meta.x$object_lon, na.rm=T)+ex
  #
  # if(latmin<(-90)) latmin <- (-90)
  # if(lonmin<(-180)) lonmin <- -180
  # if(latmax>90) latmax <- 90
  # if(lonmax>180) lonmax <- 180

  # sf_use_s2(FALSE)

  worldmap <- ne_countries(scale = 'medium', type = 'map_units', returnclass = 'sf')
  #  st_crop(xmin=lonmin, xmax=lonmax, ymax=latmax, ymin=latmin)
  meta.point <- st_as_sf(meta.x, coords=c("object_lon","object_lat"), crs=st_crs(worldmap))

  p8 <- ggplot() +
    geom_sf(data = worldmap, color=NA, fill="gray54") +
    geom_sf(data = meta.point, size=3) +
    theme_bw()

  g <- ggarrange(p1, p2, p3, p7, p5, p4, p6, p8,
                 common.legend = T, legend="bottom",
                 ncol=4, nrow=2) %>%
    annotate_figure(top=unique(x$sample_id), fig.lab.face="bold")

  # sf_use_s2(TRUE)

  return(g)
}
