#' graph.project
#'
#' Return ggplot graphics to resume the project.
#'
#' @param x bss data.table produced by "BSS_table"
#' @param metadata metadata table generated by "check_metadata"
#' @param taxo taxonomic table generated with "add_trophic" and "add_taxo"
#' @param bv.type elli, plain or riddled biovolume. default is "elli"
#' @param living.only TRUE by default
#'
#' @return A set of graphics to resume the project.
#' @export
#'
#' @examples
graph.project <- function(x, metadata, taxo, bv.type="elli", living.only=T) {

  x <- filter(x, type==bv.type) %>% merge(taxo, "object_annotation_hierarchy", all.x=T)
  t <- metadata %>% select(sample_id, object_time, object_date) %>%
    mutate(time=as.POSIXct(paste(object_date, object_time))) %>% select(sample_id, time)
  x <- merge(x, t, all.x=T)
  x$max <- bv_to_esdum(x$max)

  # RESUME OF THE PROJECT
  # ----------------------------------------------------------------------------
  div.all <- x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()
  div <- x[x$n1=="living",] %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()

  text = paste0(
    "\nALL:\n",
    "\nNumber of samples:\n",
    length(unique(x$sample_id)),
    "\nTotal absolute abundance (ind.m-3):\n",
    round(sum(x$AB, na.rm=T),4),
    "\nTotal absolute biovolume (mm3.mm-3):\n",
    round(sum(x$BV, na.rm=T),4),
    "\nShannon Index:\n",
    round(div.all,4),

    "\n\n\nLIVING ONLY:\n",
    "\nNumber of samples:\n",
    length(unique(x$sample_id[x$n1=="living"])),
    "\nTotal absolute abundance (ind.m-3):\n",
    round(sum(x$AB[x$n1=="living"], na.rm=T),4),
    "\nTotal absolute biovolume (mm3.mm-3):\n",
    round(sum(x$BV[x$n1=="living"], na.rm=T),4),
    "\nShannon Index:\n",
    round(div,4))

  print(ggplot() +
          annotate("text", x = 1, y=10, size=3, label = text) +
          theme_void())

  # BIOVOLUME TOTAL/SAMPLE
  # ----------------------------------------------------------------------------
  # live/not-live/temporary
  print(ggplot(x, aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=n1)) +
          geom_bar(stat="identity") +
          scale_fill_brewer("paired") +
          scale_y_continuous("BV (mm3.m-3)") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("All") +
          theme_minimal())

  print(ggplot(x, aes(x=reorder(sample_id, time, decreasing=T), y=AB, fill=n1)) +
          geom_bar(stat="identity") +
          scale_fill_brewer("paired") +
          scale_y_continuous("AB") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("All") +
          theme_minimal())

  # live only
  N <- length(unique(x$Sub_type[x$n1=="living"]))
  print(x %>% filter(n1=="living") %>%
          ggplot(aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Set2"))(N)) +
          scale_y_continuous("BV (mm3.m-3)") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("Living") +
          theme_minimal())

  print(x %>% filter(n1=="living") %>%
          ggplot(aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Set2"))(N)) +
          scale_y_continuous("AB") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("Living") +
          theme_minimal())

  # not live only
  N <- length(unique(x$Sub_type[x$n1=="not-living"]))
  print(x %>% filter(n1=="not-living") %>%
          ggplot(aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Set2"))(N)) +
          scale_y_continuous("BV (mm3.m-3)") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("Not-living") +
          theme_minimal())

  print(x %>% filter(n1=="not-living") %>%
          ggplot(aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Set2"))(N)) +
          scale_y_continuous("AB") +
          coord_flip() +
          xlab(NULL) +
          ggtitle("Not-living") +
          theme_minimal())

  # 4. NBSS on living
  # separer par pages !!
  # proposer de faire les graphiques par sample plus tot dans le script
  # ajouter date et time au resume nbss
  # ameliorer le resume des metadata
  # faire deja une 1ere version du script
  # ce qui est specifique a l'intercalib, il ne faut pas le mettre : WB et pompe (car en temps normal ne change pas)
  # idee de graph: chgmt couleur dans le temps ou en fonction nbss ou du sample, avec peut etre les vrais couleurs au lieu de chiffres
  # rajouter un calcul de div dans les metadata ou le resume
  if(living.only==T) x <- x %>% filter(n1=="living")

  print(x %>%
          group_by(sample_id, max, class) %>% summarise(BV=sum(BV/norm, na.rm=T), time=unique(time)) %>%
          ggplot(aes(x=max, fill=BV, y=reorder(sample_id, time, decreasing=T))) +
          geom_tile() +
          ylab(NULL) +
          scale_x_log10("Size (um)", labels=trans_format('log10',math_format(10^.x))) +
          scale_fill_viridis("NBSS (mm3.mm-3.m-3)",
                             labels=trans_format('log10',math_format(10^.x)),
                             trans="log10", option="turbo") +
          theme_minimal())

  print(x %>%
          ggplot(aes(x=max, y=BV/norm)) +
          stat_summary(fun = sum, na.rm=T, geom="line") +
          facet_wrap(~reorder(sample_id, time), strip.position="top") +
          scale_x_log10("Size (um)", labels=trans_format('log10',math_format(10^.x))) +
          scale_y_log10("NBSS (mm3.mm-3.m-3)", labels=trans_format('log10',math_format(10^.x))) +
          theme_minimal())



  # bss relatif
  N <- length(unique(x$Sub_type))
  print(x %>%
          group_by(sample_id, class) %>% mutate(rel = BV/sum(BV, na.rm=T)*100) %>%
          group_by(sample_id, class, max, Sub_type) %>% summarise(rel=sum(rel, na.rm=T)) %>%
          ggplot(aes(x=max, y=rel, fill=Sub_type)) +
          geom_col() +
          scale_fill_manual(values = colorRampPalette(brewer.pal(8, "Set2"))(N)) +
          scale_x_log10("Size (um)", labels=trans_format('log10',math_format(10^.x))) +
          facet_wrap(~sample_id, strip.position="top") +
          theme_minimal())

  # diversity
  print(x %>% group_by(object_annotation_category, sample_id) %>%
          summarise(AB=sum(AB, na.rm=T)) %>% group_by(sample_id) %>%
          summarise(Shannon=vegan::diversity(AB)) %>%
          ggplot(aes(y=sample_id, x=Shannon)) +
          geom_col() +
          ylab(NULL) +
          theme_minimal())

  # trophic levels
  x$categorie[x$Value==1] <- "Phototrophs"
  x$categorie[x$Value==1.5] <- "Mixotrophs"
  x$categorie[x$Value==2] <- "Grazers"
  x$categorie[x$Value==2.5] <- "Omnivorous"
  x$categorie[x$Value==3] <- "Predators"
  ggplot(x, aes(x=reorder(sample_id, time, decreasing=T), y=BV, fill=reorder(categorie,Value))) +
    geom_col() +
    scale_fill_brewer(palette="Set2", na.value="grey") +
    coord_flip() +
    labs(fill="Trophic level") +
    xlab(NULL) +
    ylab("Biovolume (mm3.m-3)") +
    theme_minimal()

}
